config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :vendors
  resources :purchase_typologies
  resources :tasks
  resources :projects do
    collection do
      get :completed
    end
  end
  resources :project_statuses
  resources :project_typologies
  resources :transfers do
    collection do
      get :pdfprinttransfers
    end
  end
  resources :transports
  resources :assistances
  resources :offices
  resources :categories
  resources :reports do
    collection do
      get :pdfprint
      get :pdfprintreport
    end
  end
  resources :structures
  resources :locations
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users
  root to: "home#index"
  get "home/index"
  get "home/howto"
  get "home/about"
  get "home/credits"
end

app/models/assistance.rb
class Assistance < ApplicationRecord
  belongs_to :report
  belongs_to :category, optional: true
  belongs_to :office, optional: true

  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :assistances
  has_many :purchases
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :position, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :reports
  has_many :projects
  has_many :purchases
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :position, presence: true
end

app/models/office.rb
class Office < ApplicationRecord
  has_many :assistances
  has_many :projects
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :position, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :project_typology, optional: true
  belongs_to :project_status, optional: true
  belongs_to :location, optional: true
  belongs_to :structure, optional: true
  belongs_to :office, optional: true
  belongs_to :user, optional: true

  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :start_date, presence: true
  validates :project_typology_id, presence: true
  validates :project_priority, presence: true
end

app/models/project_status.rb
class ProjectStatus < ApplicationRecord
  has_many :projects

  validates :name, presence: true
  validates :position, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :location, optional: true
  belongs_to :structure, optional: true
  belongs_to :category, optional: true
  belongs_to :purchase_typology, optional: true
  belongs_to :vendor, optional: true

  validates :request_date, presence: true
  validates :request_person, presence: true
  validates :location_id, presence: true
  validates :structure_id, presence: true
  validates :category_id, presence: true

  def set_name
    last_name = Purchase.maximum(:name)
    self.name = last_name.to_i + 1
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :location, optional: true
  belongs_to :structure, optional: true
  belongs_to :user, optional: true
  has_many :assistances, dependent: :destroy
  accepts_nested_attributes_for :assistances, reject_if: :all_blank, allow_destroy: true

  validates :date, presence: true
  validates :location_id, presence: true
  validates :structure_id, presence: true

  before_create :set_name

  def set_name
    last_name = Report.maximum(:name)
    self.name = last_name.to_i + 1
  end
end

app/models/structure.rb
class Structure < ApplicationRecord
  has_many :reports
  has_many :projects
  has_many :purchases
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :position, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :transport, optional: true
  belongs_to :user, optional: true

  validates :transfer_date, presence: true
  validates :departure, presence: true
  validates :start_point, presence: true
  validates :start_address, presence: true
  validates :arrival, presence: true
  validates :destination, presence: true
  validates :destination_address, presence: true

  before_create :set_name

  def set_name
    last_name = Transfer.maximum(:name)
    self.name = last_name.to_i + 1
  end
end

app/models/transport.rb
class Transport < ApplicationRecord
  has_many :transfers
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :position, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :recoverable, :rememberable, :validatable, :registerable
  devise :database_authenticatable

  has_many :categories, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :structures, dependent: :destroy
  has_many :offices, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :transports, dependent: :destroy
  has_many :transfers, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :project_statuses, dependent: :destroy
  has_many :project_typologies, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :purchase_typologies, dependent: :destroy
  has_many :vendors, dependent: :destroy
end

app/models/vendor.rb
class Vendor < ApplicationRecord
belongs_to :user, optional: true
has_many :purchases

validates :name, presence: true
validates :vat_number, presence: true
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def start_date?(project)
    l(project.start_date, format: '%A %d %B %Y') if project.start_date.present?
  end

  def end_date?(project)
    l(project.end_date, format: '%A %d %B %Y') if project.end_date.present?
  end

  def location?(project)
    project.location.name if project.location_id.present?
  end

  def structure?(project)
    project.structure.name if project.structure_id.present?
  end

  def office?(project)
    project.office.name if project.office_id != nil
  end

  def project_status?(project)
    project.project_status.name if project.project_status_id != nil
  end

  def project_typology?(project)
    project.project_typology.name if project.project_typology_id != nil
  end

  def completed?(project)
    project.project_status_id == 2
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def date?(report)
    l(report.date, format: '%A %d %B %Y') if report.date.present?
  end

  def location?(report)
    report.location.name if report.location_id.present?
  end

  def structure?(report)
    report.structure.name if report.structure_id.present?
  end

  def category?(assistance)
    assistance.category.name if assistance.category_id != nil
  end

  def office?(assistance)
    assistance.office.name if assistance.office_id != nil
  end

  def printable?(report)
    report.count.positive?
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-inverse navbar-fixed-top'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to inline_svg('MainLogo.svg', size: '128px * 30px', preserve_aspect_ratio: 'xMaxYMax meet'), root_path, class: 'navbar-brand' %>
    </div>
    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
      <ul class='nav navbar-nav'>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
            <i class='fas fa-clipboard-list'></i>&nbsp;&nbsp;Rapporti
            <span class='caret'></span></a>
          <ul class='dropdown-menu' role='menu'>
            <li>
              <%= link_to reports_path do %>
                <h4>
                  <i class='fas fa-pencil-alt link-awesome'></i>&nbsp;&nbsp;&nbsp;Rapporti
                </h4>
              <% end %>
            </li>
            <li>
              <%= link_to pdfprint_reports_path do %>
                <i class='fas fa-print link-awesome'></i>&nbsp;<i class='fas fa-list link-awesome'></i>&nbsp;&nbsp;&nbsp;Stampa Elenco Rapporti
              <% end %>
            </li>
            <li>
              <%= link_to pdfprintreport_reports_path do %>
                <i class='fas fa-print link-awesome'></i>&nbsp;<i class='fas fa-file-pdf link-awesome'></i>&nbsp;&nbsp;&nbsp;Stampa Rapporti Completi
              <% end %>
            </li>
            <li class='divider'></li>
            <li>
              <%= link_to locations_path do %>
                <i class='fas fa-map-signs link-awesome'></i>&nbsp;&nbsp;&nbsp;Posizioni
              <% end %>
            </li>
            <li>
              <%= link_to structures_path do %>
                <i class='far fa-building link-awesome'></i>&nbsp;&nbsp;&nbsp;Strutture
              <% end %>
            </li>
            <li class='divider'></li>
            <li>
              <%= link_to categories_path do %>
                <i class='fas fa-list link-awesome'></i>&nbsp;&nbsp;&nbsp;Categorie
              <% end %>
            </li>
            <li>
              <%= link_to offices_path do %>
                <i class='fas fa-chair link-awesome'></i>&nbsp;&nbsp;&nbsp;Uffici
              <% end %>
            </li>
          </ul>
        </li>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
            <i class='fas fa-car'></i>&nbsp;&nbsp;Trasferimenti
            <span class='caret'></span></a>
          <ul class='dropdown-menu' role='menu'>
            <li>
              <%= link_to transfers_path do %>
                <h4>
                  <i class='fas fa-space-shuttle link-awesome'></i>&nbsp;&nbsp;&nbsp;Trasferimenti
                </h4>
              <% end %>
            </li>
            <li>
              <%= link_to pdfprinttransfers_transfers_path do %>
                <i class='fas fa-print link-awesome'></i>&nbsp;<i class='fas fa-space-shuttle link-awesome'></i>&nbsp;&nbsp;&nbsp;Stampa Elenco Trasferimenti
              <% end %>
            </li>
            <li class='divider'></li>
            <li>
              <%= link_to transports_path do %>
                <i class='fas fa-truck-monster link-awesome'></i>&nbsp;&nbsp;&nbsp;Trasporti
              <% end %>
            </li>
          </ul>
        </li>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
            <i class='fas fa-project-diagram'></i>&nbsp;&nbsp;Progetti
            <span class='caret'></span></a>
          <ul class='dropdown-menu' role='menu'>
            <li>
              <%= link_to projects_path do %>
                <h4>
                  <i class='fas fa-clipboard-list link-awesome'></i>&nbsp;&nbsp;&nbsp;Progetti in corso
                </h4>
              <% end %>
            </li>
            <li>
              <%= link_to completed_projects_path do %>
                <h4>
                  <i class='fas fa-clipboard-check link-awesome'></i>&nbsp;&nbsp;&nbsp;Progetti completati
                </h4>
              <% end %>
            </li>
            <li class='divider'></li>
            <li>
              <%= link_to project_typologies_path do %>
                <i class='fas fa-toolbox link-awesome'></i>&nbsp;&nbsp;&nbsp;Tipologie Progetti
              <% end %>
            </li>
            <li>
              <%= link_to project_statuses_path do %>
                <i class='fas fa-clipboard-check link-awesome'></i>&nbsp;&nbsp;&nbsp;Stati Progetto
              <% end %>
            </li>
          </ul>
        </li>
        <!-- PURCHASE -->
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
            <i class='fas fa-shopping-cart'></i>&nbsp;&nbsp;Acquisti
            <span class='caret'></span></a>
          <ul class='dropdown-menu' role='menu'>
            <li>
              <%= link_to purchases_path do %>
                <h4>
                  <i class='fas fa-shopping-cart link-awesome'></i>&nbsp;&nbsp;&nbsp;Acquisti
                </h4>
              <% end %>
            </li>
            <li class='divider'></li>
            <li>
              <%= link_to vendors_path do %>
                <i class='fas fa-user link-awesome'></i>&nbsp;&nbsp;&nbsp;Venditori
              <% end %>
            </li>
            <li>
              <%= link_to purchase_typologies_path do %>
                <i class='far fa-credit-card link-awesome'></i>&nbsp;&nbsp;&nbsp;Tipologie Acquisto
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <li>
          <a href='#'>
            <small>
              <i class='fas fa-calendar-alt'></i>&nbsp;
              <%= l(Date.today, format: '%A %d %B %Y') %>
            </small>
          </a>
        </li>
        <li>
          <a href='#' class='hidden-xs'>
            <small>
              <i class='fas fa-user-circle'></i>
              &nbsp;&nbsp;<%= current_user.name %>&nbsp;&nbsp;<%= current_user.forename%>
              &nbsp;&nbsp;
              <i class='far fa-building'></i>
              &nbsp;&nbsp;<%= current_user.department %>
              &nbsp;&nbsp;
              <i class='fas fa-chair'></i>
              &nbsp;&nbsp;<%= current_user.office %>
            </small>
          </a>
        </li>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
            <i class='fas fa-bars'></i>
            <span class='caret'></span></a>
          <ul class='dropdown-menu' role='menu'>
            <li>
              <%= link_to home_howto_path do %>
                <i class='fas fa-book link-awesome'></i>&nbsp;&nbsp;&nbsp;Manuali
              <% end %>
            </li>
            <li>
              <%= link_to home_credits_path do %>
                <i class='fas fa-cubes link-awesome'></i>&nbsp;&nbsp;&nbsp;Crediti
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path do %>
                <i class='fas fa-user link-awesome'></i>&nbsp;&nbsp;&nbsp;Autore
              <% end %>
            </li>
            <li>
              <% if admin? %>
                <%= link_to rails_admin_path do %>
                  <i class='fas fa-cog link-awesome'></i>&nbsp;&nbsp;Amministrazione
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class='fas fa-sign-out-alt link-awesome'></i>&nbsp;&nbsp;Esci
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>