config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :vendors
  resources :purchase_typologies
  resources :tasks
  resources :projects do
    collection do
      get :completed
    end
  end
  resources :project_statuses
  resources :project_typologies
  resources :transfers do
    collection do
      get :pdfprinttransfers
    end
  end
  resources :transports
  resources :assistances
  resources :offices
  resources :categories
  resources :reports do
    collection do
      get :pdfprint
      get :pdfprintreport
    end
  end
  resources :structures
  resources :locations
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users
  root to: "home#index"
  get "home/index"
  get "home/howto"
  get "home/about"
  get "home/credits"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :project_typology, optional: true
  belongs_to :project_status, optional: true
  belongs_to :location, optional: true
  belongs_to :structure, optional: true
  belongs_to :office, optional: true
  belongs_to :user, optional: true

  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :start_date, presence: true
  validates :project_typology_id, presence: true
  validates :project_priority, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true).order(project_priority: "ASC").where(user_id: current_user.id).where(project_status_id: 1).paginate(page: params[:page], per_page: 6)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def completed
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true).order(start_date: "DESC").where(user_id: current_user.id).where(project_status_id: 2).paginate(page: params[:page], per_page: 6)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @user = current_user
    @project = @user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :start_date, :end_date, :project_typology_id, :project_priority, :project_description, :location_id, :structure_id, :office_id, :project_status_id, :user_id, tasks_attributes: Task.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def start_date?(project)
    l(project.start_date, format: '%A %d %B %Y') if project.start_date.present?
  end

  def end_date?(project)
    l(project.end_date, format: '%A %d %B %Y') if project.end_date.present?
  end

  def location?(project)
    project.location.name if project.location_id.present?
  end

  def structure?(project)
    project.structure.name if project.structure_id.present?
  end

  def office?(project)
    project.office.name if project.office_id != nil
  end

  def project_status?(project)
    project.project_status.name if project.project_status_id != nil
  end

  def project_typology?(project)
    project.project_typology.name if project.project_typology_id != nil
  end

  def completed?(project)
    project.project_status_id == 2
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |f| %>
  <% if project.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(project.errors.count, 'error') %> Non posso salvare il seguente Progetto causa errori:</h2>
      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='field'>
    <%= f.label :name, class: 'text-primary font-lite' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='field'>
    <%= f.label :start_date, class: 'text-primary font-lite' %>
    <%= f.text_field :start_date, class: 'datepicker form-control' %>
  </div>
  <div class='field'>
    <%= f.label :end_date, class: 'text-primary font-lite' %>
    <%= f.text_field :end_date, class: 'datepicker form-control' %>
  </div>
  <div class='field'>
    <%= f.label :project_typology_id, class: 'text-primary font-lite' %>
    <%= f.collection_select(:project_typology_id, ProjectTypology.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
  </div>
  <div class='field'>
    <%= f.label :project_priority, class: 'text-primary font-lite' %>
    <%= f.text_field :project_priority, class: 'form-control' %>
  </div>
  <div class='field'>
    <%= f.label :location_id, class: 'text-primary font-lite' %>
    <%= f.collection_select(:location_id, Location.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
  </div>
  <div class='field'>
    <%= f.label :structure_id, class: 'text-primary font-lite' %>
    <%= f.collection_select(:structure_id, Structure.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
  </div>
  <div class='field'>
    <%= f.label :office_id, class: 'text-primary font-lite' %>
    <%= f.collection_select(:office_id, Office.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
  </div>
  <div class='field'>
    <%= f.label :project_description, class: 'text-primary font-lite' %>
    <%= f.text_area :project_description, class: 'form-control' %>
  </div>
  <div class='field'>
    <%= f.label :project_status_id, class: 'text-primary font-lite' %>
    <%= f.collection_select(:project_status_id, ProjectStatus.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
  </div>
  <hr class='hr-gray-lighter-less'>
  <!-- NESTED -->
  <div id='tasks'>
    <%= f.fields_for :tasks do |task| %>
      <%= render 'task_fields', f: task %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association f, :tasks  do %>
        <span class='text-info'>
          <i class='fas fa-plus'></i><i class='fas fa-wrench'></i>&nbsp;&nbsp;Aggiungi Task
        </span>
      <% end %>
    </div>
  </div>
  <!-- /NESTED -->
  <hr class='hr-primary'>
  <div class='form-group'>
    <%= button_tag(type: 'submit', class: 'btn btn-success btn-sm font-lite') do %>
      <i class='fas fa-save'></i>&nbsp;&nbsp;SALVA
    <% end %>
  </div>
<% end %>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({
      language: 'it',
      todayBtn: 'linked',
      orientation: 'bottom auto'
    });
  });
</script>

app/views/projects/_task_fields.html.erb
<h4 class='text-info'>Task</h4>
<br>
<div class='panel panel-info'>
  <div class='panel-body'>
    <div class='nested-fields'>
      <div class='field'>
        <%= f.label :name, class: 'text-info font-lite' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label :start_date, class: 'text-info font-lite' %>
        <%= f.text_field :start_date, class: 'datepicker form-control'%>
      </div>
      <div class='field'>
        <%= f.label :end_date, class: 'text-info font-lite' %>
        <%= f.text_field :end_date, class: 'datepicker form-control'%>
      </div>
      <br>
      <div class='field'>
        <%= f.label :description, class: 'text-info font-lite' %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <br>
      <span class='pull-right'>
        <%= link_to_remove_association f do %>
        <span class='text-danger'>
          <i class='fas fa-trash-alt'></i>&nbsp;&nbsp;Elimina Task
        </span>
      <% end %>
    </span>
    <br>
  </div>
</div>
</div>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({
      language: 'it',
      todayBtn: 'linked',
      orientation: 'bottom auto'
    });
  });
</script>

app/views/projects/completed.html.erb
<h3>
  <%= inline_svg('project_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Progetti Completati</span>
  <span class='pull-right'>
    <h6>
      <% if admin? %>
        <%= link_to new_project_path do %>
        <%= inline_svg('project_icon.svg', size: '18px * 18px', preserve_aspect_ratio: 'xMaxYMax meet') %>
        Nuovo Progetto
      <% end %>
    <% end %>
  </h6>
</span>
</h3>
<hr class='hr-primary'>
<br>
<div class='container-fluid'>
<% @projects.each_slice(3)  do |projects| %>
  <div class='row'>
    <% projects.each  do |project| %>
      <div class='col-lg-4'>
        <div class='panel panel-primary'>
          <div class='panel-body'>
            <%= link_to project do %>
            <h3>
              <span class='text-primary'>
                <%= inline_svg('project_icon.svg', size: '26px * 26px', preserve_aspect_ratio: 'xMaxYMax meet') %>
                <%= t(project.name) %>
              </span>
            <% end %>
          </h3>
          <br>
          <small class='text-primary'>
            <i class='far fa-calendar-alt'></i>&nbsp; Inizio:&nbsp<%= start_date?(project) %>
            <br>
            <i class='far fa-calendar-alt'></i>&nbsp; Fine:&nbsp<%= end_date?(project) %>
          </small>

          <hr class='hr-gray-lighter-less'>
          <span class='pull-left'>
            <small>
              <i class='fas fa-map-marker-alt'></i>&nbsp;<%= location?(project) %>
            </small>
          </span>
          <span class='pull-right'>
            <small>
              <i class='far fa-building'></i>&nbsp;<%= structure?(project) %></small>
          </span>
          <br>
          <span class='pull-left'>
            <small>
              <i class='fas fa-toolbox'></i>&nbsp;<%= project_typology?(project) %>
            </small>
          </span>
          <span class='pull-right'>
            <small>
              <i class='fas fa-clipboard-check'></i>&nbsp;<%= project_status?(project) %></small>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>
<br>
<span class='text-centered'>
<%= will_paginate @projects, previous_label: 'Precedente', next_label: 'Prossima', renderer: BootstrapPagination::Rails %>
</span>
</div>

app/views/projects/edit.html.erb
<h3>
  <%= inline_svg('project_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Modificando il Progetto Corrente</span>
  <span class='pull-right'>
    <h6>
      <%= link_to projects_path do %>
        <span class='link-return'><i class='fas fa-arrow-left'></i></span>&nbsp;&nbsp;Ritorna alla Lista
      <% end %>
      &nbsp;|&nbsp;
      <%= link_to @project do %>
        <span class='link-view'><i class='fas fa-eye'></i></span>&nbsp;&nbsp;Visualizza Dettaglio
      <% end %>
    </h6>
  </span>
</h3>
<hr class='hr-primary'>
<br>
<%= render 'form', project: @project %>
<br>

app/views/projects/index.html.erb
<h3>
  <%= inline_svg('project_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Progetti in Corso</span>
  <span class='pull-right'>
    <h6>
      <% if admin? %>
        <%= link_to new_project_path do %>
        <%= inline_svg('project_icon.svg', size: '18px * 18px', preserve_aspect_ratio: 'xMaxYMax meet') %>
        Nuovo Progetto
      <% end %>
    <% end %>
  </h6>
</span>
</h3>
<hr class='hr-primary'>
<br>
<div class='container-fluid'>
<% @projects.each_slice(3)  do |projects| %>
  <div class='row'>
    <% projects.each  do |project| %>
      <div class='col-lg-4'>
        <div class='panel panel-primary'>
          <div class='panel-body'>
            <%= link_to project do %>
            <h3>
              <span class='text-primary'>
                <%= inline_svg('project_icon.svg', size: '26px * 26px', preserve_aspect_ratio: 'xMaxYMax meet') %>
                <%= t(project.name) %>
              </span>
            <% end %>
          </h3>
          <br>
          <small class='text-primary'>
            <i class='far fa-calendar-alt'></i>&nbsp; Inizio:&nbsp<%= start_date?(project) %>
            <br>
            <i class='far fa-calendar-alt'></i>&nbsp; Fine:&nbsp<%= end_date?(project) %>
          </small>

          <hr class='hr-gray-lighter-less'>
          <span class='pull-left'>
            <small>
              <i class='fas fa-map-marker-alt'></i>&nbsp;<%= location?(project) %>
            </small>
          </span>
          <span class='pull-right'>
            <small>
              <i class='far fa-building'></i>&nbsp;<%= structure?(project) %></small>
          </span>
          <br>
          <span class='pull-left'>
            <small>
              <i class='fas fa-toolbox'></i>&nbsp;<%= project_typology?(project) %>
            </small>
          </span>
          <span class='pull-right'>
            <small>
              <i class='fas fa-clipboard-check'></i>&nbsp;<%= project_status?(project) %></small>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>
<br>
<span class='text-centered'>
<%= will_paginate @projects, previous_label: 'Precedente', next_label: 'Prossima', renderer: BootstrapPagination::Rails %>
</span>
</div>

app/views/projects/new.html.erb
<h3>
  <%= inline_svg('project_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Crea un Nuovo Progetto</span>
  <span class='pull-right'>
    <h6>
      <%= link_to projects_path do %>
        <span class='link-return'><i class='fas fa-arrow-left'></i></span>&nbsp;&nbsp;Ritorna alla Lista
      <% end %>
    </h6>
  </span>
</h3>
<hr class='hr-primary'>
<br>
<%= render 'form', project: @project %>
<br>

app/views/projects/show.html.erb
<h3>
  <%= inline_svg('project_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'><%= @project.name %></span>
  <span class='pull-right'>
    <h6>
      <% if completed?(@project) %>
        <%= link_to completed_projects_path, title: 'Back to the List', rel: 'tooltip' do %>
          <span class='link-return'><i class='fas fa-arrow-left'></i></span>&nbsp;&nbsp;Ritorna alla Lista
        <% end %>
      <% else %>
        <%= link_to projects_path, title: 'Back to the List', rel: 'tooltip' do %>
          <span class='link-return'><i class='fas fa-arrow-left'></i></span>&nbsp;&nbsp;Ritorna alla Lista
        <% end %>
      <% end %>
      &nbsp;|&nbsp;
      <%= link_to edit_project_path(@project), title: 'Edit the current Location', rel: 'tooltip' do %>
        <span class='text-warning'><i class='fas fa-pencil-alt'></i></span>&nbsp;&nbsp;Modifica
      <% end %>
      &nbsp;|&nbsp;
      <%= link_to @project, method: :delete, data: { confirm: 'Sei sicura/o di voler eliminare il Rapporto corrente?' }, title: 'Delete the current Location', rel: 'tooltip' do %>
        <span class='text-danger'><i class='fas fa-trash-alt'></i></span>&nbsp;&nbsp;Elimina
      <% end %>
    </h6>
  </span>
</h3>
<hr class='hr-primary'>
<br>
<div class='panel panel-primary'>
  <div class='panel-body'>
    <div>
      <span class="pull-left">
        <span class='text-primary'><i class='far fa-calendar-alt'></i>&nbsp;&nbsp;Data Inizio: </span><%= start_date?(@project) %>
        &nbsp;&nbsp;
        <span class='text-primary'><i class='far fa-calendar-alt'></i>&nbsp;&nbsp;Data Fine: </span><%= end_date?(@project) %>
      </span>
      <span class="pull-right">
        <span class='text-primary'><i class='fas fa-map-marker-alt'></i>&nbsp;&nbsp;Posizione: </span><%= location?(@project) %>
        &nbsp;&nbsp;
        <span class='text-primary'><i class='far fa-building'></i>&nbsp;&nbsp;Struttura: </span><%= structure?(@project) %>
        &nbsp;&nbsp;
        <span class='text-primary'><i class='fas fa-chair'></i>&nbsp;&nbsp;Struttura: </span><%= office?(@project) %>
      </span>
      <br>
      <span class="pull-left">
        <span class='text-primary'><i class='fas fa-clipboard-list'></i>&nbsp;&nbsp;Tipologia Progetto:: </span><%= project_typology?(@project) %>
        &nbsp;&nbsp;
        <span class='text-primary'><i class="fas fa-list-ol"></i>&nbsp;&nbsp;Priorit&agrave; Progetto: </span><%= @project.project_priority %>
      </span>
      <span class="pull-right">
        <span class='text-primary'><i class="fas fa-signal"></i>&nbsp;&nbsp;Stato Progetto: </span><%= project_status?(@project) %>
        &nbsp;&nbsp;
      </span>
    </div>
  </div>
</div>
<br>
<h4>
  <span class='text-info'>
    <i class='fas fa-wrench'></i>&nbsp;Task
  </span>
</h4>
<% @project.tasks.each  do |task| %>
  <div class='panel panel-info'>
    <div class='panel-body'>
      <h4 class='text-info'><%= task.name %></h4>
      <br>
      <span class='text-info'><i class='far fa-calendar-alt'></i>&nbsp;&nbsp;Data Inizio:</span>&nbsp;<%= l(task.start_date, format: '%A %d %B %Y') %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class='text-info'><i class='far fa-calendar-alt'></i>&nbsp;&nbsp;Data Fine:</span>&nbsp;<%= l(task.end_date, format: '%A %d %B %Y') if task.end_date != nil %>
      <br><br>
      <span class='text-info'><i class="far fa-file-alt"></i>&nbsp;&nbsp;Descrizione:</span>
      <br>
      <%= task.description %>
      <br>
      <br>
    </div>
  </div>
<% end %>