config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :vendors
  resources :purchase_typologies
  resources :tasks
  resources :projects do
    collection do
      get :completed
    end
  end
  resources :project_statuses
  resources :project_typologies
  resources :transfers do
    collection do
      get :pdfprinttransfers
    end
  end
  resources :transports
  resources :assistances
  resources :offices
  resources :categories
  resources :reports do
    collection do
      get :pdfprint
      get :pdfprintreport
    end
  end
  resources :structures
  resources :locations
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users
  root to: "home#index"
  get "home/index"
  get "home/howto"
  get "home/about"
  get "home/credits"
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :location, optional: true
  belongs_to :structure, optional: true
  belongs_to :user, optional: true
  has_many :assistances, dependent: :destroy
  accepts_nested_attributes_for :assistances, reject_if: :all_blank, allow_destroy: true

  validates :date, presence: true
  validates :location_id, presence: true
  validates :structure_id, presence: true

  before_create :set_name

  def set_name
    last_name = Report.maximum(:name)
    self.name = last_name.to_i + 1
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @q = Report.ransack(params[:q])
    @reports = @q.result(distinct: true).order(date: "DESC").where(user_id: current_user.id).paginate(page: params[:page], per_page: 9)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
  end

  def pdfprint
    @user = current_user
    @q = Report.ransack(params[:q])
    @reports = @q.result(distinct: true).order(date: "DESC").where(user_id: current_user.id).paginate(page: params[:page], per_page: 100)
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: "reports/pdfprint", pdf: "pdfprint" }
      format.xlsx
    end
  end

  def pdfprintreport
    @user = current_user
    @q = Report.ransack(params[:q])
    @reports = @q.result(distinct: true).order(date: "DESC").where(user_id: current_user.id).paginate(page: params[:page], per_page: 100)
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: "reports/pdfprintreport", pdf: "pdfprintreport" }
      format.xlsx
    end
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @user = current_user
    @report = @user.reports.build(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:name, :date, :location_id, :structure_id, :user_id, assistances_attributes: Assistance.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def date?(report)
    l(report.date, format: '%A %d %B %Y') if report.date.present?
  end

  def location?(report)
    report.location.name if report.location_id.present?
  end

  def structure?(report)
    report.structure.name if report.structure_id.present?
  end

  def category?(assistance)
    assistance.category.name if assistance.category_id != nil
  end

  def office?(assistance)
    assistance.office.name if assistance.office_id != nil
  end

  def printable?(report)
    report.count.positive?
  end

end

app/views/reports/_assistance_fields.html.erb
<h4 class='text-info'>Assistenze</h4>
<br>
<div class='panel panel-info'>
  <div class='panel-body'>
    <div class='nested-fields'>
      <div class='field'>
        <%= f.label :start_time, class: 'text-info font-lite' %>
        <%= f.text_field :start_time, class: 'form-control'%>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= f.label :end_time, class: 'text-info font-lite' %>
        <%= f.text_field :end_time, class: 'form-control'%>
      </div>
      <br>
      <div class='field'>
        <%= f.label :description, class: 'text-info font-lite' %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label :note, class: 'text-info font-lite' %>
        <%= f.text_area :note, class: 'form-control' %>
      </div>
      <div class='field'>
        <%= f.label :category_id, class: 'text-info font-lite' %>
        <%= f.collection_select(:category_id, Category.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
      </div>
      <div class='field'>
        <%= f.label :office_id, class: 'text-info font-lite' %>
        <%= f.collection_select(:office_id, Office.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
      </div>
      <br>
      <span class='pull-right'>
        <%= link_to_remove_association f do %>
        <span class='text-danger'>
          <i class='fas fa-trash-alt'></i>&nbsp;&nbsp;Elimina Assistenza
        </span>
      <% end %>
    </span>
    <br>
  </div>
</div>
</div>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |f| %>
  <% if report.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(report.errors.count, 'error') %> Non posso salvare il seguente Rapporto causa errori:</h2>
      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='field'>
    <%= f.label :date, class: 'text-primary font-lite' %>
    <%= f.text_field :date, class: 'datepicker form-control' %>
  </div>
  <div class='field'>
    <%= f.label :location_id, class: 'text-primary font-lite' %>
    <%= f.collection_select(:location_id, Location.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
  </div>
  <div class='field'>
    <%= f.label :structure_id, class: 'text-primary font-lite' %>
    <%= f.collection_select(:structure_id, Structure.where(user_id: current_user.id).order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
  </div>
  <hr class='hr-gray-lighter-less'>
  <!-- NESTED -->
  <div id='assistances'>
    <%= f.fields_for :assistances do |assistance| %>
      <%= render 'assistance_fields', f: assistance %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association f, :assistances  do %>
        <span class='text-info'>
          <i class='fas fa-plus'></i><i class='fas fa-wrench'></i>&nbsp;&nbsp;Aggiungi Assistenza
        </span>
      <% end %>
    </div>
  </div>
  <!-- NESTED -->
  <hr class='hr-primary'>
  <div class='form-group'>
    <%= button_tag(type: 'submit', class: 'btn btn-success btn-sm font-lite') do %>
      <i class='fas fa-save'></i>&nbsp;&nbsp;SALVA
    <% end %>
  </div>
<% end %>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({
      language: 'it',
      todayBtn: 'linked',
      orientation: 'bottom auto'
    });
  });
</script>

app/views/reports/edit.html.erb
<h3>
  <%= inline_svg('report_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Modificando il Rapporto Corrente</span>
  <span class='pull-right'>
    <h6>
      <%= link_to reports_path do %>
        <span class='link-return'><i class='fas fa-arrow-left'></i></span>&nbsp;&nbsp;Ritorna alla Lista
      <% end %>
      &nbsp;|&nbsp;
      <%= link_to @report do %>
        <span class='link-view'><i class='fas fa-eye'></i></span>&nbsp;&nbsp;Visualizza Dettaglio
      <% end %>
    </h6>
  </span>
</h3>
<hr class='hr-primary'>
<br>
<%= render 'form', report: @report %>
<br>

app/views/reports/index.html.erb
<h3>
  <%= inline_svg('report_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Rapporti</span>
  <span class='pull-right'>
    <h6>
      <% if admin? %>
        <%= link_to new_report_path do %>
        <%= inline_svg('report_icon.svg', size: '18px * 18px', preserve_aspect_ratio: 'xMaxYMax meet') %>
        Nuovo Rapporto
      <% end %>
    <% end %>
  </h6>
</span>
</h3>
<hr class='hr-primary'>
<br>
<div class='container-fluid'>
<% @reports.each_slice(3)  do |reports| %>
  <div class='row'>
    <% reports.each  do |report| %>
      <div class='col-lg-4'>
        <div class='panel panel-primary'>
          <div class='panel-body'>
            <%= link_to report do %>
            <h3>
              <span class='text-primary'>
                <%= inline_svg('report_icon.svg', size: '26px * 26px', preserve_aspect_ratio: 'xMaxYMax meet') %>
              </span>
            <% end %>
            <span class='pull-right'>
              <small class='text-primary'>
                <i class='far fa-calendar-alt'></i>&nbsp;
                <%= date?(report) %>
              </small>
            </span>
          </h3>
          <hr class='hr-gray-lighter-less'>
          <span class='pull-left'>
            <small>
              <i class='fas fa-map-marker-alt'></i>&nbsp;<%= location?(report) %>
            </small>
          </span>
          <span class='pull-right'>
            <small>
              <i class='far fa-building'></i>&nbsp;<%= structure?(report) %></small>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>
<br>
<span class='text-centered'>
<%= will_paginate @reports, previous_label: 'Precedente', next_label: 'Prossima', renderer: BootstrapPagination::Rails %>
</span>
</div>

app/views/reports/new.html.erb
<h3>
  <%= inline_svg('report_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Crea un Nuovo Rapporto</span>
  <span class='pull-right'>
    <h6>
      <%= link_to reports_path do %>
        <span class='link-return'><i class='fas fa-arrow-left'></i></span>&nbsp;&nbsp;Ritorna alla Lista
      <% end %>
    </h6>
  </span>
</h3>
<hr class='hr-primary'>
<br>
<%= render 'form', report: @report %>
<br>

app/views/reports/pdfprint.html.erb
<h3>
  <%= inline_svg('report_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Elenco Rapporti per Stampa</span>
</h3>
<hr class='hr-primary'>
<br>
<%= search_form_for @q, id: 'search-form', url: pdfprint_reports_path do |f| %>
<div class='row'>
  <div class='col col-lg-3'>
    <div class='field'>
      <%= f.label 'Data Inizio:', class: 'font-lite' %><br>
      <%= f.text_field :date_gteq, class: 'form-control' %>
    </div>
    <div class='field'>
      <%= f.label 'Data Fine:', class: 'font-lite' %><br>
      <%= f.text_field :date_lteq, class: 'form-control' %>
    </div>
  </div>
  <div class='col col-lg-3'>
    <div class='field'>
      <%= f.label 'Posizione:', class: 'font-lite' %><br>
      <%= f.text_field :location_name_cont, class: 'form-control' %>
    </div>
    <div class='field'>
      <%= f.label 'Struttura:', class: 'font-lite' %><br>
      <%= f.text_field :structure_name_cont, class: 'form-control' %>
    </div>
  </div>
  <div class='col col-lg-3'>
    <br>
    <div class='form-actions'>
      <%= button_tag type: 'submit', class: 'btn btn-success btn-sm btn-block' do %>
      <i class='fas fa-search'></i>&nbsp;&nbsp;Cerca&nbsp;&nbsp;&nbsp;
    <% end %>
  </div>
  <br>
  <!-- PDF PRINT -->
  <% if printable?(@reports) %>
    <%= link_to pdfprint_reports_path(request.parameters.merge(format: 'pdf')), target: 'new', class: 'btn btn-info btn-sm btn-block' do %>
      <i class='fas fa-print'></i>&nbsp;&nbsp;Stampa Elenco Rapporti
    <% end %>
    <%= link_to pdfprint_reports_path(request.parameters.merge(format: 'xlsx')), target: 'new', class: 'btn btn-primary btn-sm btn-block' do %>
      <i class="far fa-file-excel"></i>&nbsp;&nbsp;Esporta Elenco Rapporti
    <% end %>
  <% end %>
</div>
</div>
<% end %>
<br>
<hr class='hr-gray-lighter-less'>
<br>
<table class='table table-striped'>
<thead>
<tr>
<th class='font-lite text-primary'>Data:</th>
<th class='font-lite text-primary'>Posizione:</th>
<th class='font-lite text-primary'>Struttura:</th>
</tr>
</thead>
<tbody>
<% @reports.each do |report| %>
<tr>
  <td><%= date?(report) %></td>
  <td><%= location?(report) %></td>
  <td><%= structure?(report) %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/reports/pdfprint.pdf.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'/>
    <%= stylesheet_link_tag wicked_pdf_asset_base64('pdfprint') %>
    <title>Elenco Rapporti</title>
  </head>
  <body>
    <div class='text-centered'>
      <%= inline_svg('pdf_header.svg', size: '680px * 18px', preserve_aspect_ratio: 'xMaxYMax meet') %>
    </div>
    <hr class='hr-primary'>
    <span class='text-primary'>
      <small>
        Elenco rapporti di assistenza di:&nbsp;&nbsp;<%= @user.name %>&nbsp;<%= @user.forename %>
      </small>
    </span>
    <span class='pull-right text-primary'>
      <small>
        <%= @user.department %>
        &nbsp;|&nbsp;
        <%= @user.office %>
      </small>
    </span>
    <br><br>
    <table class='table table-striped'>
      <thead>
        <tr>
          <th>Data:</th>
          <th>Posizione</th>
          <th>Struttura</th>
        </tr>
      </thead>
      <tbody>
        <% @reports.each do |report| %>
          <tr>
            <td><%= date?(report) %></td>
            <td><%= location?(report) %></td>
            <td><%= structure?(report) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </body>
</html>

app/views/reports/pdfprintreport.html.erb
<h3>
  <%= inline_svg('report_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Stampa Rapporti Completi</span>
</h3>
<hr class='hr-primary'>
<br>
<%= search_form_for @q, id: 'search-form', url: pdfprintreport_reports_path do |f| %>
<div class='row'>
  <div class='col col-lg-3'>
    <div class='field'>
      <%= f.label 'Data Inizio:', class: 'font-lite' %><br>
      <%= f.text_field :date_gteq, class: 'form-control' %>
    </div>
    <div class='field'>
      <%= f.label 'Data Fine:', class: 'font-lite' %><br>
      <%= f.text_field :date_lteq, class: 'form-control' %>
    </div>
  </div>
  <div class='col col-lg-3'>
    <div class='field'>
      <%= f.label 'Posizione:', class: 'font-lite' %><br>
      <%= f.text_field :location_name_cont, class: 'form-control' %>
    </div>
    <div class='field'>
      <%= f.label 'Struttura:', class: 'font-lite' %><br>
      <%= f.text_field :structure_name_cont, class: 'form-control' %>
    </div>
  </div>
  <div class='col col-lg-3'>
    <br>
    <div class='form-actions'>
      <%= button_tag type: 'submit', class: 'btn btn-success btn-sm btn-block' do %>
      <i class='fas fa-search'></i>&nbsp;&nbsp;Cerca&nbsp;&nbsp;&nbsp;
    <% end %>
  </div>
  <br>
  <!-- PDF PRINT -->
  <% if printable?(@reports) %>
    <%= link_to pdfprintreport_reports_path(request.parameters.merge(format: 'pdf')), target: 'new', class: 'btn btn-info btn-sm btn-block' do %>
    <i class='fas fa-print'></i>&nbsp;&nbsp;Stampa Elenco Rapporti Completi
    <% end %>
    <%= link_to pdfprintreport_reports_path(request.parameters.merge(format: 'xlsx')), target: 'new', class: 'btn btn-primary btn-sm btn-block' do %>
    <i class="far fa-file-excel"></i>&nbsp;&nbsp;Esporta Elenco Rapporti Completi
    <% end %>
<% end %>
</div>
</div>
<% end %>
<br>
<hr class='hr-gray-lighter-less'>
<br>
<table class='table table-striped'>
<tbody>
<% @reports.each do |report| %>
<tr>
  <td>
    <i class='far fa-calendar-alt text-primary'></i>&nbsp;<%= date?(report) %>
    &nbsp;&nbsp;&nbsp;
    <i class='fas fa-map-marker-alt text-primary'></i>&nbsp;<%= location?(report) %>
    &nbsp;&nbsp;&nbsp;
    <i class='far fa-building text-primary'></i>&nbsp;<%= structure?(report) %>
    <br>
    <% report.assistances.each  do |assistance| %>
      <span class='text-info'>
        <i class='far fa-clock'></i>&nbsp;&nbsp;Ora Inizio:</span>&nbsp;<%= l(assistance.start_time, format: '%H : %M') %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class='text-info'>
        <i class='far fa-clock'></i>&nbsp;&nbsp;Ora Fine:</span>&nbsp;<%= l(assistance.end_time, format: '%H : %M') %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class='text-info'>
        <i class='fas fa-chair'></i>&nbsp;&nbsp;Ufficio:</span>&nbsp;<%= office?(assistance) %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class='text-info'>
        <i class='fas fa-list'></i>&nbsp;&nbsp;Categoria:</span>&nbsp;<%= category?(assistance) %>
      <br>
      <span class='text-info'>Descrizione:</span>&nbsp;<small class="font-lite"><%= assistance.description %></small>
      <br>
      <span class='text-info'>Note:</span>&nbsp;<small class="font-lite"><%= assistance.note %></small>
      <br><br>
    <% end %>
  </td>
</tr>
<% end %>
</tbody>
</table>

app/views/reports/pdfprintreport.pdf.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'/>
    <%= stylesheet_link_tag wicked_pdf_asset_base64('pdfprint') %>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.8.1/css/all.css' integrity='sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf' crossorigin='anonymous'>
    <title>Elenco Rapporti</title>
  </head>
  <body>
    <% @reports.each do |report| %>
      <div class='text-centered'>
        <%= inline_svg('pdf_header.svg', size: '680px * 18px', preserve_aspect_ratio: 'xMaxYMax meet') %>
      </div>
      <hr class='hr-primary'>
      <span class='text-primary'>
        <small>
          Rapporto di Assistenza di:&nbsp;&nbsp;<%= @user.name %>&nbsp;<%= @user.forename %>
        </small>
      </span>
      <span class='pull-right text-primary'>
        <small>
          <%= @user.department %>
          &nbsp;|&nbsp;
          <%= @user.office %>
        </small>
      </span>
      <br><br>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Data:</th>
            <th>Posizione</th>
            <th>Struttura</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= date?(report) %></td>
            <td><%= location?(report) %></td>
            <td><%= structure?(report) %></td>
          </tr>
        </tbody>
      </table>
      <div class='report'>
        <i class='fas fa-tools'></i>&nbsp;Interventi:<br><br>
        <% report.assistances.each  do |assistance| %>
          <span class='text-primary'>
            <i class='far fa-clock'></i>&nbsp;&nbsp;Ora Inizio:</span>&nbsp;<%= l(assistance.start_time, format: '%H : %M') %>
          &nbsp;&nbsp;&nbsp;
          <span class='text-primary'>
            <i class='far fa-clock'></i>&nbsp;&nbsp;Ora Fine:</span>&nbsp;<%= l(assistance.end_time, format: '%H : %M') %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <span class='text-primary'>
            <i class='fas fa-chair'></i>&nbsp;&nbsp;Ufficio:</span>&nbsp;<%= office?(assistance) %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <span class='text-primary'>
            <i class='fas fa-list'></i>&nbsp;&nbsp;Categoria:</span>&nbsp;<%= category?(assistance) %>
          <br><br>
          <span class='text-primary'>Descrizione:</span>&nbsp;<br>
          <%= assistance.description %>
          <br><br>
          <span class='text-primary'>Note:</span>&nbsp;<br>
          <%= assistance.note %>
          <hr class='hr-gray-lighter-less'>
        <% end %>
      </div>
      <br>
      <p style='page-break-before: always'></body>
    <% end %>
  </html>

app/views/reports/show.html.erb
<h3>
  <%= inline_svg('report_icon.svg', size: '32px * 32px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  &nbsp;<span class='text-primary'>Rapporto n°:&nbsp;<%= @report.name %></span>
  <span class='pull-right'>
    <h6>
      <%= link_to reports_path, title: 'Back to the List', rel: 'tooltip' do %>
        <span class='link-return'><i class='fas fa-arrow-left'></i></span>&nbsp;&nbsp;Ritorna alla Lista
      <% end %>
      &nbsp;|&nbsp;
      <%= link_to edit_report_path(@report), title: 'Edit the current Location', rel: 'tooltip' do %>
        <span class='text-warning'><i class='fas fa-pencil-alt'></i></span>&nbsp;&nbsp;Modifica
      <% end %>
      &nbsp;|&nbsp;
      <%= link_to @report, method: :delete, data: { confirm: 'Sei sicura/o di voler eliminare il Rapporto corrente?' }, title: 'Delete the current Location', rel: 'tooltip' do %>
        <span class='text-danger'><i class='fas fa-trash-alt'></i></span>&nbsp;&nbsp;Elimina
      <% end %>
    </h6>
  </span>
</h3>
<hr class='hr-primary'>
<br>
<div class='panel panel-primary'>
  <div class='panel-body'>
    <div>
      <span class='text-primary'><i class='far fa-calendar-alt'></i>&nbsp;&nbsp;Data: </span><%= date?(@report) %>
      &nbsp;
      <span class='text-primary'><i class='fas fa-map-marker-alt'></i>&nbsp;&nbsp;Posizione: </span><%= location?(@report) %>
      &nbsp;
      <span class='text-primary'><i class='far fa-building'></i>&nbsp;&nbsp;Struttura: </span><%= structure?(@report) %>
    </div>
  </div>
</div>
<br>
<h4>
  <span class='text-info'>
    <i class='fas fa-wrench'></i>&nbsp;Assistenze
  </span>
</h4>
<% @report.assistances.each  do |assistance| %>
  <div class='panel panel-info'>
    <div class='panel-body'>
      <span class='text-info'><i class='far fa-clock'></i>&nbsp;&nbsp;Ora Inizio:</span>&nbsp;<%= l(assistance.start_time, format: '%H : %M') %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class='text-info'><i class='far fa-clock'></i>&nbsp;&nbsp;Ora Fine:</span>&nbsp;<%= l(assistance.end_time, format: '%H : %M') %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class='text-info'><i class='fas fa-chair'></i>&nbsp;&nbsp;Ufficio:</span>&nbsp;<%= office?(assistance) %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class='text-info'><i class='fas fa-list'></i>&nbsp;&nbsp;Categoria:</span>&nbsp;<%= category?(assistance) %>
      <br>
      <br>
      <span class='text-info'>Descrizione:</span>&nbsp;
      <hr class='hr-gray-lighter-less'>
      <%= assistance.description %>
      <br>
      <br>
      <span class='text-info'>Note:</span>&nbsp;
      <hr class='hr-gray-lighter-less'>
      <%= assistance.note %>
    </div>
  </div>
<% end %>